name: sparcs-ci-seminar-assignment
on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Login to DockerHub
                uses: docker/login-action@v1
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}

            -   name: Docker build and push
                uses: docker/build-push-action@v2
                with:
                    push: true
                    tags: ${{ secrets.DOCKERHUB_USERNAME }}/sparcs-ci-seminar-assignment:latest
            
    pull:
        name: Pull Docker image and run
        runs-on: ubuntu-latest
        needs: [build]
        steps:
            -   name: Pull Docker image from registry and run
                uses: appleboy/ssh-action@master
                with:
                    host: ${{ secrets.SSH_HOST }}
                    username: ${{ secrets.SSH_USERNAME }}
                    password: ${{ secrets.SSH_PASSWORD }}
                    port: ${{ secrets.SSH_PORT }}
                    script: |
                        docker pull ${{ secrets.DOCKERHUB_USERNAME }}/sparcs-ci-seminar-assignment:latest
                        docker run --name sparcs-ci-seminar-assignment -d -p 3001:3001 ${{ secrets.DOCKERHUB_USERNAME }}/sparcs-ci-seminar-assignment:latest
                        docker rmi $(docker images -f "dangling=true" -q)